# -*- coding: utf-8 -*-
"""AIML_Project_Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pV3RnFVi4b3XosY65GgW9CB0OSIYk428

**Fundamental in AI&ML - Project "Creating my first Chatbot"**

1. Importing the needed libraries for creation of a Chatbot
- numpy to do nmerical calculations
- nltk is a NLP library
- String library to handle strings
- randomise the greetings
"""

import numpy as np
import nltk
import string
import random

"""2. Import and readin gthe training data (Corpus)

Bringing and making sure the program has access to the corpus
"""
data='''# Artificial Intelligence
Artificial intelligence (AI) is technology that enables computers and machines to simulate human learning, comprehension, problem solving, decision making, creativity and autonomy.

Applications and devices equipped with AI can see and identify objects, understand human language, learn from new information, and act independently (e.g., self-driving cars).

# Machine Learning
Machine learning involves creating models by training algorithms to make predictions or decisions based on data. Techniques include regression, decision trees, random forest, SVMs, KNN, clustering, and neural networks.

Supervised learning uses labeled data, while unsupervised learning finds hidden patterns. Neural networks mimic the human brain with interconnected nodes.

# Deep Learning
Deep learning is a subset of ML using deep neural networks with multiple hidden layers. It enables large-scale learning without human intervention, powering NLP, computer vision, and pattern recognition.

Variants include semi-supervised learning, self-supervised learning, reinforcement learning, and transfer learning.

# Generative AI
Generative AI refers to deep learning models that create original text, images, video, or audio. Key model types:
- Variational Autoencoders (VAEs)
- Diffusion Models
- Transformers (e.g., GPT, Copilot, BERT, Bard, Midjourney)

Generative AI workflow: Training → Tuning → Generation & Evaluation.

# AI Agents
AI agents are autonomous programs that perform tasks without human intervention. Agentic AI coordinates multiple agents to achieve complex goals.

# Benefits of AI
- Automation of repetitive tasks
- Enhanced decision-making
- Fewer human errors
- 24x7 availability
- Reduced physical risks

# AI Use Cases
- Customer service chatbots
- Fraud detection
- Personalized marketing
- Recruitment automation
- Application modernization
- Predictive maintenance

# AI Challenges & Risks
- Data risks (poisoning, bias, cyberattacks)
- Model risks (tampering, theft)
- Operational risks (drift, governance failures)
- Ethical/legal risks (bias, privacy violations)

# AI Ethics & Governance
Principles include:
- Explainability
- Fairness & inclusion
- Robustness & security
- Accountability & transparency
- Privacy & compliance

# Weak AI vs Strong AI
- Weak AI (Narrow AI): performs specific tasks (e.g., Siri, Alexa).
- Strong AI (AGI): theoretical, human-level intelligence across tasks.
'''
with open('chatbot.txt', mode='w', encoding='utf-8', newline='') as file:
    file.write(data)

f=open('chatbot.txt','r',errors = 'ignore')
raw_doc=f.read()
raw_doc=raw_doc.lower() #Function to convert all input to lower case
nltk.download('punkt') #Using the punkt tokenizer from nltk module
nltk.download('wordnet') #Using the WordNet dictionary to find meaning or rooting
nltk.download('punkt_tab') # Download the missing 'punkt_tab' resource
sent_tokens = nltk.sent_tokenize(raw_doc) #Converts the document to list of sentences
word_tokens = nltk.word_tokenize(raw_doc) #Converts the document to list of words

"""To check the working of sent_tokens"""
#sent_tokens[:2]

"""To check the working of word_tokens"""
#word_tokens[:2]

"""3. Data Processing

Note : WordNet is an interface to a large lexical database of the English.
It functions as a combination of a dictionary and thesaurus.
"""

lemmer = nltk.stem.WordNetLemmatizer()
def LemTokens(tokens):
    return[lemmer.lemmatize(token) for token in tokens]
remove_punct_dict = dict((ord(punct), None)for punct in string.punctuation)
def lemnormalize(text):
    return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))

"""4. Defining the greeting text and replies to the greetings"""

GREET_INPUTS = ("hello", "hi", "greetings", "hey", "good morning")
GREET_RESPONSES = ("hi", "hey", "*nods*", "yes", "hello","I'm glad that you are talking to me")
def greet(sentence):
    for word in sentence.split():
        if word.lower() in GREET_INPUTS:
            return random.choice(GREET_RESPONSES)

"""4. Now to see the response generation
- tfidf stands for 'Term Frequency and Inverse document frequecy'
1. Term frequency states how many times a word is repeated
2. Inverse document frequency says how rarely a word occurs
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def response(user_response):
    robo1_response = ' '
    TfidfVec = TfidfVectorizer(tokenizer = lemnormalize, stop_words = 'english')
    tfidf = TfidfVec.fit_transform(sent_tokens)
    vals = cosine_similarity(tfidf[-1], tfidf)
    idx = vals.argsort()[0][-2]
    flat = vals.flatten()
    flat.sort()
    req_tfidf = flat[-2]
    if(req_tfidf==0):
        robo1_response = robo1_response+" I am sorry! I don't understand you "
        return robo1_response
    else:
        robo1_response = robo1_response + sent_tokens[idx]
        return robo1_response

import warnings
warnings.filterwarnings("ignore", category=UserWarning)

"""Defining the coversation's starting and the ending protocol"""

flag = True
print("BOT : My name is Rudhran, Let's have a conversation!, If you want to exit at anytime, just type Bye!")
while(flag==True):
    user_response = input()
    user_response = user_response.lower()
    if(user_response != "bye!"):
        if(user_response == 'thanks' or user_response == 'thank you'):
            flag=False
            print("BOT : You are welcome..!!")
        else:
            if(greet(user_response)!= None):
                print("BOT : "+greet(user_response))
            else:
                sent_tokens.append(user_response)
                word_tokens = word_tokens+nltk.word_tokenize(user_response)
                final_words = list(set(word_tokens))
                print("BOT : ", end="")
                print(response(user_response))
                sent_tokens.remove(user_response)
    else:
        flag = False
        print("BOT: Goodbye! Take care, ready to help at your call.")
